-- Create a table for public bookings
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  check_in date not null,
  check_out date not null,
  guests integer default 2
);

-- Enable Row Level Security (RLS)
alter table bookings enable row level security;

-- Policy to allow anyone (anon) to INSERT a booking
-- NOTE: We do NOT allow SELECT (reading) for privacy reasons.
-- The frontend must NOT call .select() after insert.
create policy "Allow public inserts"
on bookings for insert
to anon
with check (true);
