-- Create a table for public bookings
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  check_in date not null,
  check_out date not null,
  guests integer default 2
);

-- Enable Row Level Security (RLS)
alter table bookings enable row level security;

-- Create a policy to allow anyone (anon) to insert bookings
create policy "Allow public inserts"
on bookings for insert
to anon
with check (true);

-- Optional: Create a policy to allow reading own bookings (demo simplified)
-- For now, we only allow insertion. Reading would require auth or admin role.
